/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Song = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'album' : IDL.Text,
  'audioUrl' : IDL.Text,
  'genre' : IDL.Text,
  'artist' : IDL.Text,
  'coverUrl' : IDL.Text,
});
export const PlaylistView = IDL.Record({
  'id' : IDL.Nat,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'songIds' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addSongToPlaylist' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'createPlaylist' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deletePlaylist' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteSong' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'filterSongsByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
  'getAllPlaylists' : IDL.Func([], [IDL.Vec(PlaylistView)], ['query']),
  'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'getLikedSongs' : IDL.Func([IDL.Principal], [IDL.Vec(Song)], ['query']),
  'getPlaylistSongs' : IDL.Func([IDL.Nat], [IDL.Vec(Song)], ['query']),
  'getUserPlaylists' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PlaylistView)],
      ['query'],
    ),
  'isSongLiked' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Bool], ['query']),
  'likeSong' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'removeSongFromPlaylist' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
  'searchSongsByArtist' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
  'searchSongsByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
  'unlikeSong' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'uploadSong' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Song = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'album' : IDL.Text,
    'audioUrl' : IDL.Text,
    'genre' : IDL.Text,
    'artist' : IDL.Text,
    'coverUrl' : IDL.Text,
  });
  const PlaylistView = IDL.Record({
    'id' : IDL.Nat,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'songIds' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addSongToPlaylist' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'createPlaylist' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deletePlaylist' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteSong' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'filterSongsByGenre' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
    'getAllPlaylists' : IDL.Func([], [IDL.Vec(PlaylistView)], ['query']),
    'getAllSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'getLikedSongs' : IDL.Func([IDL.Principal], [IDL.Vec(Song)], ['query']),
    'getPlaylistSongs' : IDL.Func([IDL.Nat], [IDL.Vec(Song)], ['query']),
    'getUserPlaylists' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PlaylistView)],
        ['query'],
      ),
    'isSongLiked' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Bool], ['query']),
    'likeSong' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'removeSongFromPlaylist' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Bool], []),
    'searchSongsByArtist' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
    'searchSongsByTitle' : IDL.Func([IDL.Text], [IDL.Vec(Song)], ['query']),
    'unlikeSong' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'uploadSong' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };