/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PlaylistView {
  'id' : bigint,
  'owner' : Principal,
  'name' : string,
  'songIds' : Array<bigint>,
}
export interface Song {
  'id' : bigint,
  'title' : string,
  'duration' : bigint,
  'album' : string,
  'audioUrl' : string,
  'genre' : string,
  'artist' : string,
  'coverUrl' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addSongToPlaylist' : ActorMethod<[bigint, bigint], boolean>,
  'createPlaylist' : ActorMethod<[string], bigint>,
  'deletePlaylist' : ActorMethod<[bigint], boolean>,
  'deleteSong' : ActorMethod<[bigint], boolean>,
  'filterSongsByGenre' : ActorMethod<[string], Array<Song>>,
  'getAllPlaylists' : ActorMethod<[], Array<PlaylistView>>,
  'getAllSongs' : ActorMethod<[], Array<Song>>,
  'getLikedSongs' : ActorMethod<[Principal], Array<Song>>,
  'getPlaylistSongs' : ActorMethod<[bigint], Array<Song>>,
  'getUserPlaylists' : ActorMethod<[Principal], Array<PlaylistView>>,
  'isSongLiked' : ActorMethod<[Principal, bigint], boolean>,
  'likeSong' : ActorMethod<[bigint], boolean>,
  'removeSongFromPlaylist' : ActorMethod<[bigint, bigint], boolean>,
  'searchSongsByArtist' : ActorMethod<[string], Array<Song>>,
  'searchSongsByTitle' : ActorMethod<[string], Array<Song>>,
  'unlikeSong' : ActorMethod<[bigint], boolean>,
  'uploadSong' : ActorMethod<
    [string, string, string, string, bigint, string, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];